# Generated by Django 2.2.14 on 2020-07-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timestamp',
            new_name='name',
        ),
    ]
